#!/usr/bin/env python3
"""Combine the uStock manual chapters into a single Markdown file and a Word (.docx) file."""

import re
import os
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

MANUAL_DIR = "/Users/golamhabibpalash/Documents/Dev/Projects/uStock/docs/manual"
CHAPTERS = [
    "00-about-this-manual.md",
    "01-introduction.md",
    "02-getting-started.md",
    "03-company-and-settings.md",
    "04-products-and-catalogue.md",
    "05-customers-and-sales.md",
    "06-vendors-and-purchasing.md",
    "07-inventory-and-stock-movements.md",
    "08-pricing.md",
    "09-reports.md",
    "10-users-roles-and-security.md",
    "11-administration-and-logs.md",
    "12-utilities-todo.md",
    "13-everyday-tasks-and-conventions.md",
    "14-troubleshooting-and-faq.md",
    "15-glossary.md",
]

TITLE = "uStock User Manual"
SUBTITLE = "Inventory & Warehouse Management System"
VERSION_LINE = "Version 1.0.0  —  Issued 2026-09-08"


def gh_slug(text):
    """Approximate GitHub's heading-anchor algorithm (no hyphen collapsing)."""
    s = text.strip().lower()
    s = re.sub(r"[^\w\s-]", "", s)
    s = s.replace(" ", "-")
    return s


# ---------------------------------------------------------------------------
# 1. Build the combined Markdown file
# ---------------------------------------------------------------------------
file_to_anchor = {}
raw = {}
for fn in CHAPTERS:
    with open(os.path.join(MANUAL_DIR, fn), encoding="utf-8") as fh:
        text = fh.read()
    raw[fn] = text
    m = re.search(r"^#\s+(.+)$", text, re.M)
    file_to_anchor[fn] = gh_slug(m.group(1)) if m else gh_slug(fn)


def fix_links(text):
    def repl(match):
        label, target = match.group(1), match.group(2)
        base = target.split("#")[0]
        if base in file_to_anchor:
            return f"[{label}](#{file_to_anchor[base]})"
        return match.group(0)
    return re.sub(r"\[([^\]]+)\]\(([^)]+)\)", repl, text)


combined = [
    f"# {TITLE}\n",
    f"*{SUBTITLE}*\n",
    f"{VERSION_LINE}\n",
    "\n> This is the consolidated edition of the uStock User Manual. It is generated by "
    "joining the chapter files in `docs/manual/`. To edit, change the individual chapter "
    "files and regenerate, or edit this file directly.\n",
    "\n---\n",
]
for fn in CHAPTERS:
    combined.append("\n\n")
    combined.append(fix_links(raw[fn]).strip())
    combined.append("\n")

combined_md = "\n".join(combined) + "\n"
out_md = os.path.join(MANUAL_DIR, "uStock-User-Manual.md")
with open(out_md, "w", encoding="utf-8") as fh:
    fh.write(combined_md)
print("wrote", out_md)


# ---------------------------------------------------------------------------
# 2. Build the Word document
# ---------------------------------------------------------------------------
doc = Document()

# base style
normal = doc.styles["Normal"]
normal.font.name = "Calibri"
normal.font.size = Pt(11)

for section in doc.sections:
    section.top_margin = Inches(1)
    section.bottom_margin = Inches(1)
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)


def add_footer_page_numbers(document):
    footer = document.sections[0].footer
    p = footer.paragraphs[0]
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run()
    fld1 = OxmlElement("w:fldChar"); fld1.set(qn("w:fldCharType"), "begin")
    instr = OxmlElement("w:instrText"); instr.set(qn("xml:space"), "preserve"); instr.text = "PAGE"
    fld2 = OxmlElement("w:fldChar"); fld2.set(qn("w:fldCharType"), "end")
    run._r.append(fld1); run._r.append(instr); run._r.append(fld2)


add_footer_page_numbers(doc)

# ---- Title page ----
t = doc.add_paragraph()
t.alignment = WD_ALIGN_PARAGRAPH.CENTER
for _ in range(6):
    doc.paragraphs[-1].add_run("\n")
r = t.add_run(TITLE)
r.bold = True
r.font.size = Pt(30)
sub = doc.add_paragraph()
sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
rs = sub.add_run(SUBTITLE)
rs.italic = True
rs.font.size = Pt(14)
ver = doc.add_paragraph()
ver.alignment = WD_ALIGN_PARAGRAPH.CENTER
ver.add_run(VERSION_LINE).font.size = Pt(11)
note = doc.add_paragraph()
note.alignment = WD_ALIGN_PARAGRAPH.CENTER
rn = note.add_run("End-user operating manual  •  Generated from docs/manual/")
rn.font.size = Pt(9)
rn.font.color.rgb = RGBColor(0x66, 0x66, 0x66)
doc.add_page_break()

# ---- Table of contents (Word field) ----
doc.add_heading("Contents", level=1)
toc_p = doc.add_paragraph()
run = toc_p.add_run()
f1 = OxmlElement("w:fldChar"); f1.set(qn("w:fldCharType"), "begin")
it = OxmlElement("w:instrText"); it.set(qn("xml:space"), "preserve")
it.text = r'TOC \o "1-3" \h \z \u'
f2 = OxmlElement("w:fldChar"); f2.set(qn("w:fldCharType"), "separate")
tt = OxmlElement("w:t"); tt.text = "Right-click and choose “Update Field” to build the table of contents."
f3 = OxmlElement("w:fldChar"); f3.set(qn("w:fldCharType"), "end")
run._r.append(f1); run._r.append(it); run._r.append(f2); run._r.append(tt); run._r.append(f3)
doc.add_page_break()


# ---- inline formatting ----
INLINE_RE = re.compile(
    r"(\*\*.+?\*\*|`[^`]+`|\[[^\]]+\]\([^)]+\)|(?<!\*)\*(?!\s)(?:[^*]+?)\*(?!\*))"
)


def add_inline(paragraph, text):
    text = text.replace(" ", " ")
    pos = 0
    for m in INLINE_RE.finditer(text):
        if m.start() > pos:
            paragraph.add_run(text[pos:m.start()])
        tok = m.group(0)
        if tok.startswith("**") and tok.endswith("**"):
            paragraph.add_run(tok[2:-2]).bold = True
        elif tok.startswith("`") and tok.endswith("`"):
            r = paragraph.add_run(tok[1:-1])
            r.font.name = "Consolas"
            r.font.size = Pt(9.5)
        elif tok.startswith("[") and "](" in tok:
            label = tok[1:tok.index("]")]
            r = paragraph.add_run(label)
            r.font.color.rgb = RGBColor(0x1A, 0x5F, 0xB4)
            r.underline = True
        elif tok.startswith("*") and tok.endswith("*"):
            paragraph.add_run(tok[1:-1]).italic = True
        else:
            paragraph.add_run(tok)
        pos = m.end()
    if pos < len(text):
        paragraph.add_run(text[pos:])


def strip_md_table_row(line):
    line = line.strip()
    if line.startswith("|"):
        line = line[1:]
    if line.endswith("|"):
        line = line[:-1]
    return [c.strip() for c in line.split("|")]


def shade_cell(cell, hex_fill):
    tcPr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_fill)
    tcPr.append(shd)


# ---- render each chapter ----
for ci, fn in enumerate(CHAPTERS):
    lines = raw[fn].split("\n")
    i = 0
    n = len(lines)
    in_code = False
    code_buf = []
    while i < n:
        line = lines[i]

        # fenced code
        if line.lstrip().startswith("```"):
            if not in_code:
                in_code = True
                code_buf = []
            else:
                in_code = False
                p = doc.add_paragraph()
                p.paragraph_format.left_indent = Inches(0.2)
                r = p.add_run("\n".join(code_buf))
                r.font.name = "Consolas"
                r.font.size = Pt(9)
                r.font.color.rgb = RGBColor(0x33, 0x33, 0x33)
            i += 1
            continue
        if in_code:
            code_buf.append(line)
            i += 1
            continue

        stripped = line.strip()

        if not stripped:
            i += 1
            continue

        # headings
        hm = re.match(r"^(#{1,6})\s+(.*)$", stripped)
        if hm:
            level = len(hm.group(1))
            htext = hm.group(2).strip()
            if level == 1:
                if ci != 0:
                    doc.add_page_break()
                h = doc.add_heading("", level=1)
                add_inline(h, htext)
            else:
                h = doc.add_heading("", level=min(level, 4))
                add_inline(h, htext)
            i += 1
            continue

        # horizontal rule
        if re.match(r"^(-{3,}|\*{3,}|_{3,})$", stripped):
            i += 1
            continue

        # blockquote
        if stripped.startswith(">"):
            qtext = stripped.lstrip(">").strip()
            p = doc.add_paragraph()
            p.paragraph_format.left_indent = Inches(0.3)
            add_inline(p, qtext)
            for run in p.runs:
                run.italic = True
                run.font.color.rgb = RGBColor(0x55, 0x55, 0x55)
            i += 1
            continue

        # table
        if stripped.startswith("|") and i + 1 < n and re.match(r"^\|?[\s:*-]+\|", lines[i + 1].strip()):
            header = strip_md_table_row(lines[i])
            i += 2
            rows = []
            while i < n and lines[i].strip().startswith("|"):
                rows.append(strip_md_table_row(lines[i]))
                i += 1
            ncols = len(header)
            table = doc.add_table(rows=1, cols=ncols)
            table.style = "Table Grid"
            table.alignment = WD_TABLE_ALIGNMENT.LEFT
            table.autofit = True
            hdr = table.rows[0].cells
            for c, txt in enumerate(header):
                hdr[c].text = ""
                pr = hdr[c].paragraphs[0]
                add_inline(pr, txt)
                for run in pr.runs:
                    run.bold = True
                shade_cell(hdr[c], "E7E6E6")
            for r_ in rows:
                cells = table.add_row().cells
                for c in range(ncols):
                    val = r_[c] if c < len(r_) else ""
                    cells[c].text = ""
                    add_inline(cells[c].paragraphs[0], val)
            doc.add_paragraph()
            continue

        # lists
        lm = re.match(r"^(\s*)([-*+]|\d+\.)\s+(.*)$", line)
        if lm:
            indent = len(lm.group(1))
            marker = lm.group(2)
            content = lm.group(3).strip()
            ordered = bool(re.match(r"\d+\.", marker))
            if ordered:
                style = "List Number" if indent < 2 else "List Number 2"
            else:
                style = "List Bullet" if indent < 2 else "List Bullet 2"
            try:
                p = doc.add_paragraph(style=style)
            except KeyError:
                p = doc.add_paragraph(style="List Bullet")
            add_inline(p, content)
            i += 1
            continue

        # plain paragraph (join wrapped lines until blank / structural)
        buf = [stripped]
        i += 1
        while i < n:
            nxt = lines[i]
            ns = nxt.strip()
            if (not ns or ns.startswith("#") or ns.startswith("|")
                    or ns.startswith(">") or ns.startswith("```")
                    or re.match(r"^(\s*)([-*+]|\d+\.)\s+", nxt)
                    or re.match(r"^(-{3,}|\*{3,}|_{3,})$", ns)):
                break
            buf.append(ns)
            i += 1
        p = doc.add_paragraph()
        add_inline(p, " ".join(buf))

out_docx = os.path.join(MANUAL_DIR, "uStock-User-Manual.docx")
doc.save(out_docx)
print("wrote", out_docx)
